# users.yaml

apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: alice
spec:
  profile:
    displayName: Alice Frontend
    email: alice@example.com
  memberOf: [frontend]

---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: bob
spec:
  profile:
    displayName: Bob Backend
    email: bob@example.com
  memberOf: [backend]

---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: charlie
spec:
  profile:
    displayName: Charlie DevOps
    email: charlie@example.com
  memberOf: [devops]

---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: diana
spec:
  profile:
    displayName: Diana BI
    email: diana@example.com
  memberOf: [bi]

---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: eve
spec:
  profile:
    displayName: Eve QA
    email: eve@example.com
  memberOf: [qa]

---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: frank
spec:
  profile:
    displayName: Frank Líder
    email: frank@example.com
  memberOf: [lideres]

---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: grace
spec:
  profile:
    displayName: Grace Professora
    email: grace@example.com
  memberOf: [professores]

---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: heidi
spec:
  profile:
    displayName: Heidi IA
    email: heidi@example.com
  memberOf: [ia]

---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: ivan
spec:
  profile:
    displayName: Ivan Administrativo
    email: ivan@example.com
  memberOf: [administrativo]
